### ISSUE TITLE
【Terraformドライバ】Module素材集メニューで不備のあるModule素材を登録後、ファイル形式を変更するとシステムエラーが発生する

### ISSUE THREAD

**Issue by tomoka-abe** [exastro-suite/exastro-it-automation#2487]
### バグの説明
Terraform-Cloud/EP・Terraform-CLIのModule素材集メニューで不備のあるModule素材を登録後、ファイル形式を変更するとシステムエラーが発生する

### 再現方法
1. Terraform-Cloud/EP・Terraform-CLIのModule素材集メニューに移動します。
2. 不備のあるModule素材を作成し、登録します。
例
![不備のあるModule素材例](https://github.com/exastro-suite/exastro-it-automation/assets/130961669/9c8ee398-8825-4db4-9b0a-c1c035446921)
3. 「編集」をクリックし、名称欄、モードを変更します。
例
![不備のあるModule素材例_変更後](https://github.com/exastro-suite/exastro-it-automation/assets/130961669/b1a34f31-86b2-48df-b196-bb5b838d96bd)
4. 「編集確認」をクリックします。
5. システムエラーが発生します。

### 本来期待する挙動
システムエラーが発生しない。

### 動作環境
2.5

**Comment by tomoka-abe** [comment]
エラー文：
`[2024-05-30 12:07:51,656][INFO][ORGANIZATION_ID:xxxx][WORKSPACE_ID:xxxx][USER_ID:xxxx] [ts=2024-05-30T03:07:51.631Z][api-start] url:POST:http://ita-api-organization:8000/api/xxxx/workspaces/xxxx/ita/menu/module_files_terraform_cloud_ep/maintenance/all/
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lark/parsers/lalr_parser_state.py", line 77, in feed_token
    action, arg = states[state][token.type]
KeyError: '$END'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/exastro/common_libs/api/util.py", line 168, in wrapper
    controller_res = func(*args, **kwargs)
  File "/exastro/controllers/menu_maintenance_all_controller.py", line 82, in maintenance_all
    raise e
  File "/exastro/controllers/menu_maintenance_all_controller.py", line 80, in maintenance_all
    result_data = menu_maintenance_all.rest_maintenance_all(objdbca, menu, parameters)
  File "/exastro/common_libs/common/menu_maintenance_all.py", line 45, in rest_maintenance_all
    status_code, result, msg = objmenu.rest_maintenance_all(parameters)
  File "/exastro/common_libs/loadtable/load_table.py", line 1250, in rest_maintenance_all
    raise e
  File "/exastro/common_libs/loadtable/load_table.py", line 1225, in rest_maintenance_all
    tmp_result = self.exec_maintenance(parameters, target_uuid, cmd_type)
  File "/exastro/common_libs/loadtable/load_table.py", line 1495, in exec_maintenance
    tmp_exec = self.exec_menu_before_validate(copy.deepcopy(target_menu_option))
  File "/exastro/common_libs/loadtable/load_table.py", line 2074, in exec_menu_before_validate
    tmp_exec = eval(eval_str)
  File "<string>", line 1, in <module>
  File "/exastro/common_libs/validate/valid_80105.py", line 57, in external_valid_menu_before
    hcl2json.executeParse(True)
  File "/exastro/common_libs/terraform_driver/common/Hcl2Json.py", line 69, in executeParse
    parse_result = hcl2.loads(file_read.read())
  File "/usr/lib/python3.9/site-packages/hcl2/api.py", line 27, in loads
    tree = hcl2.parse(text + "\n")
  File "/usr/lib/python3.9/site-packages/lark/lark.py", line 658, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/usr/lib/python3.9/site-packages/lark/parser_frontends.py", line 104, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/usr/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 42, in parse
    return self.parser.parse(lexer, start)
  File "/usr/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 88, in parse
    return self.parse_from_state(parser_state)
  File "/usr/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 111, in parse_from_state
    raise e
  File "/usr/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 105, in parse_from_state
    return state.feed_token(end_token, True)
  File "/usr/lib/python3.9/site-packages/lark/parsers/lalr_parser_state.py", line 80, in feed_token
    raise UnexpectedToken(token, expected, state=self, interactive_parser=None)
lark.exceptions.UnexpectedToken: Unexpected token Token('$END', '') at line 1, column 4.
Expected one of: 
        * LBRACE


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "/usr/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "/usr/lib/python3.9/site-packages/connexion/decorators/validation.py", line 196, in wrapper
    response = function(request)
  File "/usr/lib/python3.9/site-packages/connexion/decorators/validation.py", line 399, in wrapper
    return function(request)
  File "/usr/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 120, in wrapper
    return function(**kwargs)
  File "/exastro/common_libs/api/util.py", line 176, in wrapper
    return exception_response(e)
  File "/exastro/common_libs/api/util.py", line 128, in exception_response
    if isinstance(args[0], AppException):
IndexError: tuple index out of range`
